# Generated by Django 4.0.5 on 2022-06-22 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inmo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cliente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compra',
            name='numero',
            field=models.CharField(default=56958800127, max_length=500),
            preserve_default=False,
        ),
    ]
