# Generated by Django 4.0.5 on 2022-06-22 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmo', '0002_compra_cliente_compra_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='propiedad_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inmo.propiedad'),
        ),
    ]
