# Generated by Django 4.0.5 on 2022-06-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmo', '0003_alter_compra_propiedad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='propiedad_id',
            field=models.CharField(default=5, max_length=5),
            preserve_default=False,
        ),
    ]
